### ISSUE TITLE
std::cout?

### ISSUE THREAD

**Issue by AKstatistics** [jeaye/stdman#12]
Why can't I find things like cout?
```
man std::cout
No manual entry for std::cout
```

I get entries for std::string and std::iostream so I know the man pages installed.

**Comment by jeaye** [comment]
@AKstatistics The man pages, for better or worse, follow the naming of the cppref pages. That is, it's not `man std::cout` you want, it's `man std::cout,std::wcout`. Typically, if you just type `man foo<TAB>`, you'll end up with what you want.

I wouldn't mind changing this, in the future, but it's not an immediate issue.
