### ISSUE TITLE
fails to install on arch linux

### ISSUE THREAD

**Issue by agauniyal** [jeaye/stdman#14]

**Comment by jeaye** [comment]
Some info would be helpful! Did you run `./configure && [sudo] make install`? What was the output? What user did you run as? Are there any peculiarities or non-standard bits about your system?

stdman has been tested (and was developed) on Arch Linux.

**Comment by agauniyal** [comment]
Yeah sorry for not providing the essential details. I'm talking about the `aur/stdman-git` package `(v0.2.r3.15f2ae8-1)`. I'm attaching the log below.

**Comment by agauniyal** [comment]
~ ❯ yaourt stdman
1 aur/stdman 0.2-1 (1) (0.08)
    Formatted C++11/14 stdlib man pages (cppreference)
2 aur/stdman-git v0.2.r3.15f2ae8-1 (2) (0.25)
    Formatted C++11/14 stdlib man pages (cppreference)
==> Enter n° of packages to be installed (ex: 1 2 3 or 1-3)
==> -------------------------------------------------------
==> 2


==> Downloading stdman-git PKGBUILD from AUR...
x .SRCINFO
x PKGBUILD
stdman-git v0.2.r3.15f2ae8-1  (2015-09-15 18:27)
( Unsupported package: Potentially dangerous ! )
==> Edit PKGBUILD ? [Y/n] ("A" to abort)
==> ------------------------------------
==> n

==> stdman-git dependencies:
 - git (already installed) [makedepend]


==> Continue building stdman-git ? [Y/n]
==> ------------------------------------
==> y

==> Building and installing package
==> Making package: stdman-git v0.2.r3.15f2ae8-1 (Mon Mar 28 00:08:35 IST 2016)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning stdman git repo...
Cloning into bare repository '/tmp/yaourt-tmp-agauniyal/aur-stdman-git/stdman'...
remote: Counting objects: 20148, done.
remote: Total 20148 (delta 0), reused 0 (delta 0), pack-reused 20148
Receiving objects: 100% (20148/20148), 7.82 MiB | 9.00 KiB/s, done.
Resolving deltas: 100% (17616/17616), done.
Checking connectivity... done.
==> Validating source files with md5sums...
    stdman ... Skipped
==> Extracting sources...
  -> Creating working copy of stdman git repo...
Cloning into 'stdman'...
done.
==> Starting pkgver()...
==> Updated version: stdman-git v0.2.r11.101ae0c-1
==> Starting build()...
Configuring stdman
Platform: Linux

Reference location: ./reference/en/cpp
Install prefix: /usr
Install data prefix: /usr/share
Install man prefix: /usr/share/man
Temporary man location: ./man
Generation will be on 8 threads

Populating Makefile
Done configuring stdman

To install, use `make install` with the appropriate permissions for your prefix
==> Entering fakeroot environment...
==> Starting package()...
Installing from ./man to /tmp/yaourt-tmp-agauniyal/aur-stdman-git/pkg/stdman-git//usr/share/man/man3
Done; it's advised to run 'sudo mandb' now.
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issue...
==> Creating package "stdman-git"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: stdman-git v0.2.r11.101ae0c-1 (Mon Mar 28 00:20:20 IST 2016)
==> Cleaning up...

==> Continue installing stdman-git ? [Y/n]
==> [v]iew package contents [c]heck package with namcap
==> ---------------------------------------------------
==> y

loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) stdman-git-v0.2.r11.101ae0c-1

Total Installed Size:  2.67 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                           [########################################] 100%
(1/1) checking package integrity                                         [########################################] 100%
(1/1) loading package files                                              [########################################] 100%
(1/1) checking for file conflicts                                        [########################################] 100%
error: failed to commit transaction (conflicting files)
stdman-git: /usr/share/man/man3/std::allocator.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::allocator_traits.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::array.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::atomic.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::atomic_flag.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::auto_ptr.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::back_insert_iterator.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::bad_alloc.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::bad_cast.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::bad_exception.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::bad_function_call.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::bad_typeid.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::bad_weak_ptr.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::basic_filebuf.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::basic_fstream.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::basic_ifstream.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::basic_ios.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::basic_iostream.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::basic_istream.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::basic_istringstream.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::basic_ofstream.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::basic_ostream.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::basic_ostringstream.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::basic_regex.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::basic_streambuf.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::basic_string.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::basic_stringbuf.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::basic_stringstream.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::bernoulli_distribution.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::binary_function.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::binary_negate.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::binomial_distribution.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::bitset.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::cauchy_distribution.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::char_traits.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::chi_squared_distribution.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::chrono::duration.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::chrono::duration_values.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::chrono::time_point.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::chrono::treat_as_floating_point.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::codecvt.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::codecvt_base.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::codecvt_byname.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::collate.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::collate_byname.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::complex.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::condition_variable.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::ctype.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::ctype_base.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::ctype_byname.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::default_delete.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::deque.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::discard_block_engine.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::discrete_distribution.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::divides.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::domain_error.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::enable_shared_from_this.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::equal_to.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::error_code.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::error_condition.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::exception.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::experimental::any.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::experimental::bad_optional_access.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::experimental::basic_string_view.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::experimental::filesystem::path.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::experimental::optional.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::exponential_distribution.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::extreme_value_distribution.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::filebuf.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::fisher_f_distribution.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::forward_list.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::fpos.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::front_insert_iterator.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::fstream.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::future.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::future_error.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::gamma_distribution.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::geometric_distribution.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::greater.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::greater_equal.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::gslice.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::gslice_array.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::hash.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::ifstream.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::independent_bits_engine.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::indirect_array.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::initializer_list.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::insert_iterator.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::integer_sequence.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::integral_constant.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::invalid_argument.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::ios.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::ios_base.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::iostream.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::is_abstract.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::is_arithmetic.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::is_array.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::is_bind_expression.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::is_class.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::is_compound.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::is_const.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::is_empty.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::is_enum.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::is_error_code_enum.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::is_error_condition_enum.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::is_final.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::is_floating_point.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::is_function.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::is_fundamental.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::is_integral.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::is_literal_type.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::is_lvalue_reference.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::is_member_function_pointer.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::is_member_object_pointer.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::is_member_pointer.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::is_null_pointer.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::is_object.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::is_placeholder.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::is_pod.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::is_pointer.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::is_polymorphic.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::is_reference.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::is_rvalue_reference.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::is_scalar.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::is_standard_layout.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::is_trivial.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::is_union.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::is_void.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::is_volatile.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::istream.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::istream_iterator.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::istreambuf_iterator.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::istringstream.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::iterator.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::length_error.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::less.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::less_equal.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::linear_congruential_engine.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::list.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::locale.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::lock_guard.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::logic_error.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::logical_and.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::logical_not.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::logical_or.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::lognormal_distribution.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::map.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::mask_array.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::match_results.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::mersenne_twister_engine.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::messages.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::messages_base.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::messages_byname.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::minus.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::modulus.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::money_base.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::money_get.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::money_put.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::moneypunct.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::moneypunct_byname.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::move_iterator.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::multimap.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::multiplies.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::multiset.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::mutex.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::negate.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::negative_binomial_distribution.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::nested_exception.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::normal_distribution.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::not_equal_to.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::num_get.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::num_put.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::numeric_limits.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::numpunct.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::numpunct_byname.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::ofstream.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::once_flag.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::ostream.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::ostream_iterator.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::ostreambuf_iterator.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::ostringstream.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::out_of_range.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::overflow_error.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::owner_less.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::pair.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::piecewise_constant_distribution.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::piecewise_linear_distribution.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::plus.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::pointer_to_binary_function.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::pointer_to_unary_function.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::pointer_traits.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::poisson_distribution.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::priority_queue.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::promise.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::queue.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::random_device.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::range_error.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::ratio.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::ratio_equal.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::ratio_not_equal.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::raw_storage_iterator.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::recursive_mutex.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::reference_wrapper.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::regex_error.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::regex_iterator.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::regex_token_iterator.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::regex_traits.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::reverse_iterator.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::runtime_error.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::scoped_allocator_adaptor.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::seed_seq.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::set.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::shared_future.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::shared_lock.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::shared_ptr.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::shared_timed_mutex.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::shuffle_order_engine.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::slice.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::slice_array.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::stack.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::streambuf.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::string.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::stringbuf.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::stringstream.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::student_t_distribution.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::sub_match.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::subtract_with_carry_engine.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::system_error.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::thread.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::time_base.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::time_get.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::time_get_byname.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::time_put.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::time_put_byname.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::tuple.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::type_index.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::type_info.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::unary_function.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::unary_negate.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::underflow_error.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::uniform_int_distribution.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::uniform_real_distribution.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::unique_lock.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::unique_ptr.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::unordered_map.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::unordered_multimap.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::unordered_multiset.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::unordered_set.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::uses_allocator.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::valarray.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::vector.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::wbuffer_convert.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::weak_ptr.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::weibull_distribution.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::wfilebuf.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::wfstream.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::wifstream.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::wios.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::wiostream.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::wistream.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::wistringstream.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::wofstream.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::wostream.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::wostringstream.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::wstreambuf.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::wstring.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::wstring_convert.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::wstringbuf.3.gz exists in filesystem
stdman-git: /usr/share/man/man3/std::wstringstream.3.gz exists in filesystem
Errors occurred, no packages were upgraded.
==> WARNING: Your packages are saved in /tmp/yaourt-tmp-agauniyal

**Comment by agauniyal** [comment]
Also this was the output when I had installed it fresh, as well as on every other try.

**Comment by agauniyal** [comment]
Output of `sudo mandb` after installation and before another try -

```
~ ❯ sudo mandb
Purging old database entries in /usr/share/man...
Processing manual pages under /usr/share/man...
Purging old database entries in /usr/share/man/id...
Processing manual pages under /usr/share/man/id...
Purging old database entries in /usr/share/man/pl.ISO8859-2...
Processing manual pages under /usr/share/man/pl.ISO8859-2...
Purging old database entries in /usr/share/man/pl.UTF-8...
Processing manual pages under /usr/share/man/pl.UTF-8...
Purging old database entries in /usr/share/man/de.UTF-8...
Processing manual pages under /usr/share/man/de.UTF-8...
Purging old database entries in /usr/share/man/sv...
Processing manual pages under /usr/share/man/sv...
Purging old database entries in /usr/share/man/fr.UTF-8...
Processing manual pages under /usr/share/man/fr.UTF-8...
Purging old database entries in /usr/share/man/zh_CN...
Processing manual pages under /usr/share/man/zh_CN...
Purging old database entries in /usr/share/man/jp...
Processing manual pages under /usr/share/man/jp...
Purging old database entries in /usr/share/man/cs...
Processing manual pages under /usr/share/man/cs...
Purging old database entries in /usr/share/man/it.ISO8859-1...
Processing manual pages under /usr/share/man/it.ISO8859-1...
Purging old database entries in /usr/share/man/tr...
Processing manual pages under /usr/share/man/tr...
Purging old database entries in /usr/share/man/it...
Processing manual pages under /usr/share/man/it...
Purging old database entries in /usr/share/man/de...
Processing manual pages under /usr/share/man/de...
Purging old database entries in /usr/share/man/pt_BR...
Processing manual pages under /usr/share/man/pt_BR...
Purging old database entries in /usr/share/man/ru.KOI8-R...
Processing manual pages under /usr/share/man/ru.KOI8-R...
Purging old database entries in /usr/share/man/zh_TW...
Processing manual pages under /usr/share/man/zh_TW...
Purging old database entries in /usr/share/man/fr.ISO8859-1...
Processing manual pages under /usr/share/man/fr.ISO8859-1...
Purging old database entries in /usr/share/man/pt...
Processing manual pages under /usr/share/man/pt...
Purging old database entries in /usr/share/man/nl...
Processing manual pages under /usr/share/man/nl...
Purging old database entries in /usr/share/man/ru...
Processing manual pages under /usr/share/man/ru...
Purging old database entries in /usr/share/man/ko...
Processing manual pages under /usr/share/man/ko...
Purging old database entries in /usr/share/man/hu...
Processing manual pages under /usr/share/man/hu...
Purging old database entries in /usr/share/man/da...
Processing manual pages under /usr/share/man/da...
Purging old database entries in /usr/share/man/es...
Processing manual pages under /usr/share/man/es...
Purging old database entries in /usr/share/man/ja...
Processing manual pages under /usr/share/man/ja...
Purging old database entries in /usr/share/man/ru.UTF-8...
Processing manual pages under /usr/share/man/ru.UTF-8...
Purging old database entries in /usr/share/man/it.UTF-8...
Processing manual pages under /usr/share/man/it.UTF-8...
Purging old database entries in /usr/share/man/fr...
Processing manual pages under /usr/share/man/fr...
Purging old database entries in /usr/share/man/pl...
Processing manual pages under /usr/share/man/pl...
Purging old database entries in /usr/share/man/sl...
Processing manual pages under /usr/share/man/sl...
Processing manual pages under /usr/local/man...
0 man subdirectories contained newer manual pages.
0 manual pages were added.
0 stray cats were added.
0 old database entries were purged.
```

**Comment by agauniyal** [comment]
also my man pages don't look as clean as in your gif. I'll post a screenshot soon.

**Comment by agauniyal** [comment]
![2016-03-28-002828_1366x768_scrot](https://cloud.githubusercontent.com/assets/7630575/14067166/d8447714-f47b-11e5-95ef-39ce7adf558a.png)

**Comment by jeaye** [comment]
@agauniyal Those packages are unofficial; I've never seen them before. Please try installing as the README suggests and let me know.

Your man pages don't look clean because they're not the stdman pages; they're the GCC ones. As the readme says, *"If you're getting 'no manual entry for std::foo' or you're seeing the libstdc++ man pages (characterized by a huge list of typedefs when you run man std::string), see the following."* [here](https://github.com/jeaye/stdman#troubleshooting).

**Comment by agauniyal** [comment]
works that way, thanks :smile:
