### ISSUE TITLE
Some of the man pages don't include the examples from the website

### ISSUE THREAD

**Issue by reverseila** [jeaye/stdman#44]
I don't see examples in the man pages. Am I missing something?

**Comment by reverseila** [comment]
Oh, I just noticed that examples are included, but not all of them. Maybe an update issue.
For example, the man page for [`std::vector::at`](https://github.com/jeaye/stdman/blob/478d353c73bec79bbbad833a31c50eecd4578b46/man/std::vector::at.3) does not include the following example from the [website](https://en.cppreference.com/w/cpp/container/vector/at):

```cpp
#include <iostream>
#include <vector>
 
int main()
{
    std::vector<int> data = { 1, 2, 4, 5, 5, 6 };
 
    // Set element 1
    data.at(1) = 88;
 
    // Read element 2
    std::cout << "Element at index 2 has value " << data.at(2) << '\n';
 
    std::cout << "data size = " << data.size() << '\n';
 
    try {
        // Set element 6
        data.at(6) = 666;
    } catch (std::out_of_range const& exc) {
        std::cout << exc.what() << '\n';
    }
 
    // Print final values
    std::cout << "data:";
    for (int elem : data)
        std::cout << " " << elem;
    std::cout << '\n';
}
```

**Comment by jeaye** [comment]
This is likely just due to the manpages being out of date. If the examples were added to cppref after the last time the manpages were generated, we won't have them. Feel free to regenerate and submit a PR!

**Comment by reverseila** [comment]
Thanks for the guide! I sent a pull request.
I guess we can close this issue.
